[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["scanner/**"]

[deploy]
startCommand = "./scanner"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1
